### ISSUE TITLE
how to work

### ISSUE THREAD

**Issue by ecomcodeLab** [lpsm-dev/auto-earn-pre#22]
hi i downloaded the script
and i know a little pypthon it starts chrome and opens login page i try to login but it cclose to fast the browser

i cant find were i have to put in my account details
can you say how

**Comment by lpsm-dev** [comment]
You need to setup `PRESEARCH_EMAIL` and `PRESEARCH_PASSWORD` environment variables on your terminal, install all packages with `pip install -r requirements.txt` and run the python script `python src/main.py --driver_type=chrome`

**Comment by lpsm-dev** [comment]
Hi @badplay! In the `README.md` file I put some details about this. If you have any questions, please reopen this issue.
