### ISSUE TITLE
It's not working in headless mode

### ISSUE THREAD

**Issue by imabutahersiddik** [lpsm-dev/auto-earn-pre#23]
Can you make it working in headless mode for linux and support for chromium, it will be better to use, I know risk of it but it still better.

**Comment by lpsm-dev** [comment]
I will implement this feature soon. Today this automation has some problems because the pre-search interface has changed some elements. If you contribute I will love it

**Comment by lpsm-dev** [comment]
I think headless mode is not an option based on this context. by the way, you will need to interact with the interface to resolve captcha + 2Auth.

**Comment by lpsm-dev** [comment]
I have implemented the chrome option already.
